apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    service: frontend-service  
spec:
  replicas: 1
  selector: 
    matchLabels:
      service: frontend-service
  template:
    metadata:
      labels:
        service: frontend-service
        api: external        
    spec:
      containers:
      - image: tomphamns/udagram-frontend:v1
        name: frontend-service
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always