apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-service
  labels:
    service: reverseproxy-service  
spec:
  replicas: 1
  selector: 
    matchLabels:
      service: reverseproxy-service
  template:
    metadata:
      labels:
        service: reverseproxy-service
      name: backend-user
    spec:
      containers:
      - image: tomphamns/reverseproxy:v1
        name: reverseproxy-service
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 80
      restartPolicy: Always